---
- name: just a testing
  hosts: all
  gather_facts: false
  tasks:
    - name: copy shell script to remote server
      copy:
        src: ./test.sh
        dest: ~/
    - name: starting patch for linux
      shell: sh ~/test.sh
